/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        TwitterBot bot = new TwitterBot();
        bot.startListen(927734664730525697L,
                136865608L,
                68867011L,
                85500625L,
                1666144568L,
                4922989969L,
                574879168L,
                1584008426L,
                2583568380L,
                458112133L,
                3380801739L,
                898583681475895296L,
                2842241861L,
                1703293896L,
                768571115450933248L,
                824327363257217024L,
                2967671155L,
                97280932L,
                1966268922L,
                125771415L);
    }

}
