import java.util.Date;

public class Event {
    public String address = null;
    public String lat = null;
    public String lon = null;
    public String eventDate = null;
    public String originalTweet = null;
    public String linkToTweet = null;
    public String twitterHandle = null;
    public String merchantName = null;
    public String merchantLogo = null;
    public String twitterID = null;
    public String autoGeneratedByNLP;

    public Event() {
        autoGeneratedByNLP = "1";
    }
}
