var cmpe272App = angular.module("cmpe272App",[]);

cmpe272App.controller('homectrl', function($scope, $http) {

    $scope.rows = [];
    $scope.valueee;
    var data = {};
    $http.get('/profile').then(function(req, res){
        console.log('profile res %j', req);
        data = {"twitterHandle":"@cmpe272group22"};
        postMethod(data);
    });
    //var data = {"twitterHandle":"nlnn"};

    

    $scope.orderByField = 'eventName';
    $scope.reverseSort = false;
    // $scope.selectRow = parseData[0];
    // console.log($scope.selectRow);

    $scope.setTempItem = function(item) {
        $scope.selectRow = item;
        //$scope.dataRow = item;
        console.log($scope.selectRow);
    }

    console.log();
    this.event = {
        addr: ''
    };

    //Submit Form
    $scope.getVal = function() {
       // alert("Hello, " + $scope.addr);
        $http.get('https://maps.googleapis.com/maps/api/geocode/json?address=' + 
                $scope.addr + '&key=AIzaSyCzHsjgIycpJS54hxSo2ipPVk3sOWys8z8')
            .then(function(_results){
                alert(_results.data);
                $scope.queryResults = _results.data.results;
                $scope.geodata = $scope.queryResults[0].geometry;
            }, 
            function error(_error){
                $scope.queryError = _error;
            })
    }
    this.submit = function() {
        console.log('User clicked register', this.event);
     };
    $('#form1').submit = function() {
        console.log('form submit');
        data = {};
        $http.get('https://maps.googleapis.com/maps/api/geocode/json?address=' + 
                    $scope.addr + '&key=AIzaSyCzHsjgIycpJS54hxSo2ipPVk3sOWys8z8')
            .then(function(_results){
                alert(_results.data);
                //$scope.queryResults = _results.data.results;
                var lat = _results.data.results[0].geometry.location.lat();
                var lon = _results.data.results[0].geometry.location.lng();
                // sendCORD(lat, lon);
                data["lat"] = lat;
                data["lon"] = lon;
                data["address"] = $scope.addr;
                data["originalTweet"] = "";
                data["linkToTweet"] = "";
                data["eventDate"] = $scope.edate;
                data["twitterHandle"] = "";
                data["merchantName"] = "";
                data["merchantLogo"] = "";
                data["twitterID"] = "";
                data["autoGeneratedByNLP"] = "0";
                $http.post('http://52.53.249.123:3000/create', data, config).
                then(function(response) {
                    console.log("posted inserted successfully");
                }).catch(function(response) {
                    console.error("error in posting" + response);
                });
            }, 
            function error(_error){
                $scope.queryError = _error;
            })
        // function sendCORD(lat, lon) {
        //     data["lat"] = lat;
        //     data["lon"] = lon;
        //     data["address"] = $("#tbUnm").val();
        // }
        return false;
    }
    
    function postMethod( data) {
        var config = {
            headers : {
                'Content-Type': 'application/json'
            }
        };
        console.log(data);
        
        //$http.post('http://52.53.249.123:3000/fetch', data, config).
        $http.post('/fetch', data, config).
        then(function(response) {
            console.log("posted successfully");
            var data = JSON.stringify(response);
            parseData = $.parseJSON(data);
            console.log(parseData['data']);
            $scope.rows = parseData['data'];
            $scope.selectRow = $scope.rows[0];
            //$scope.dataRow = $scope.rows[0];
        }).catch(function(response) {
            console.error("error in posting" + response);
        });
    }
    
});
