var cmpe272App = angular.module("cmpe272App",[]);

cmpe272App.controller('homectrl', function($scope, $http) {

    $scope.rows = [];
    // $scope.user = window.user;
    console.log('user-id ' + window.username);
    // var data = {};
    $scope.display = window.displayName;

    data = {"twitterHandle":"@"+window.username};
    postMethod(data);
    //var data = {"twitterHandle":"nlnn"};

    

    $scope.orderByField = 'eventName';
    $scope.reverseSort = false;
    // $scope.selectRow = parseData[0];
    // console.log($scope.selectRow);

    $scope.setTempItem = function(item) {
        $scope.selectRow = item;
        //$scope.dataRow = item;
        console.log($scope.selectRow);
    }

    console.log();
    this.event = {
        addr: ''
    };

    //Submit Form
    // $scope.getVal = function() {
    //    // alert("Hello, " + $scope.addr);
    //     $http.get('https://maps.googleapis.com/maps/api/geocode/json?address=' + 
    //             $scope.addr + '&key=AIzaSyCzHsjgIycpJS54hxSo2ipPVk3sOWys8z8')
    //         .then(function(_results){
    //             alert(_results.data);
    //             $scope.queryResults = _results.data.results;
    //             $scope.geodata = $scope.queryResults[0].geometry;
    //         }, 
    //         function error(_error){
    //             $scope.queryError = _error;
    //         })
    // }
    this.submit = function() {
        console.log('User clicked register', this.event);
     };
    $scope.formsubmit = function() {
        console.log('form submit');
        data = {};
        var config = {
            headers : {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        };
                getLatLon($scope.addr, function(latlon) {
                    data["lat"] = latlon.lat;
                    data["lon"] = latlon.lon;
                    data["address"] = $scope.addr;
                    data["originalTweet"] = "";
                    data["linkToTweet"] = "";
                    data["eventDate"] = new Date($scope.edate).toISOString().slice(0, 19).replace('T', ' ');
                    data["twitterHandle"] = "@"+window.username;
                    data["merchantName"] = $scope.mname;
                    data["merchantLogo"] = "";
                    data["twitterID"] = $scope.tid;
                    data["autoGeneratedByNLP"] = "0";
                    $http.post('/create', data, config).
                    then(function(response) {
                        console.log("posted inserted successfully");
                        document.getElementById('form1').submit();
                    }).catch(function(response) {
                        console.error("error in posting" + response);
                    });
                });
                
            // }, 
            // function error(_error){
            //     $scope.queryError = _error;
            // })
        // function sendCORD(lat, lon) {
        //     data["lat"] = lat;
        //     data["lon"] = lon;
        //     data["address"] = $("#tbUnm").val();
        // }
        return false;
    }
    
    function postMethod( data) {
        var config = {
            headers : {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        };
        console.log(data);
        
        //$http.post('/fetch', data, config).
        $http.post('/fetch', data, config).
        then(function(response) {
            console.log("posted successfully");
            var data = JSON.stringify(response);
            parseData = $.parseJSON(data);
            console.log(parseData['data']);
            $scope.rows = parseData['data'];
            $scope.selectRow = $scope.rows[0];
            //$scope.dataRow = $scope.rows[0];
        }).catch(function(response) {
            console.error("error in posting" + response);
        });
    }

    function postXML( data) {
        var config = {
            headers : {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        };
        console.log(data);
        
        //$http.post('http://52.53.249.123:3000/fetch', data, config).
        $http.post('/map', data, config).
        then(function(response) {
            console.log("posted successfully");
            var data = JSON.stringify(response);
            parseData = $.parseJSON(data);
            console.log(parseData['data']);
            $scope.rows = parseData['data'];
            $scope.selectRow = $scope.rows[0];
            //$scope.dataRow = $scope.rows[0];
        }).catch(function(response) {
            console.error("error in posting" + response);
        });
    }
    
});
